greeting:
  - hello
  - hi
  - hey
  - greetings
  - good morning
  - good afternoon
  - good evening

farewell:
  - goodbye
  - bye
  - see you
  - farewell
  - good night

question:
  - what
  - how
  - why
  - when
  - where
  - who
  - can you
  - could you

agreement:
  - yes
  - yeah
  - sure
  - okay
  - ok
  - alright
  - agree
  - correct

disagreement:
  - no
  - nope
  - disagree
  - incorrect
  - wrong

thank:
  - thank
  - thanks
  - appreciate
  - grateful

help:
  - help
  - assist
  - support
  - guide
