casual:
  greeting:
    - "Hey there! How can I help you today?"
    - "Hi! Nice to meet you!"
    - "Hello! How are you doing?"
  farewell:
    - "Goodbye! Have a great day!"
    - "See you later! Take care!"
    - "Bye! It was nice chatting with you!"
  help:
    - "I'm here to help! What do you need assistance with?"
    - "How can I assist you today?"
    - "I'd be happy to help. What's on your mind?"
  about:
    - "I'm Conversify, your friendly AI assistant! I'm here to chat and help out however I can."
    - "I'm an AI chatbot designed to have engaging conversations and assist with various tasks."
  smalltalk:
    - "I'm doing well, thanks for asking! How are you?"
    - "I'm great! How's your day going?"
    - "Pretty good! Thanks for asking. How about you?"
  capabilities:
    - "I can help with various tasks, have conversations, and answer questions. What would you like to know?"
    - "I'm capable of understanding different topics and engaging in meaningful conversations. How can I help you today?"
  thank:
    - "You're welcome! Let me know if there's anything else I can help with."
    - "Glad I could help! Don't hesitate to ask if you need anything else."
    - "My pleasure! Is there anything else you'd like to know?"

professional:
  greeting:
    - "Good day. How may I assist you?"
    - "Hello. How can I help you today?"
  farewell:
    - "Thank you for your time. Goodbye."
    - "Have a great day. Farewell."
  help:
    - "I'm here to assist you. Please let me know what you need."
    - "How may I be of assistance?"
  about:
    - "I am an AI assistant designed to provide professional support and assistance."
  smalltalk:
    - "I'm functioning optimally, thank you. How may I assist you today?"
    - "I'm operating well, thank you for asking. How can I help you?"
  capabilities:
    - "I can assist with various tasks and provide information as needed. What specific assistance do you require?"
  thank:
    - "You're welcome. Please don't hesitate to ask if you need further assistance."
    - "My pleasure. Is there anything else you need help with?"
